# Generated by Django 6.0.6 on 2026-07-29 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Где выполнять привычку', max_length=255, verbose_name='Место')),
                ('time', models.TimeField(help_text='В какое время выполнять (ЧЧ:ММ)', verbose_name='Время выполнения')),
                ('action', models.CharField(help_text='Что делать', max_length=255, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная привычка')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вознаграждение')),
                ('periodicity', models.PositiveIntegerField(default=1, help_text='От 1 до 7 дней', verbose_name='Периодичность (в днях)')),
                ('execution_time', models.PositiveIntegerField(help_text='Не больше 120 секунд', verbose_name='Время выполнения (секунды)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная привычка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to', to='habits.habit', verbose_name='Связанная приятная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-created_at'],
            },
        ),
    ]
